package cz.cloudy.fxengine.core;

import cz.cloudy.fxengine.interfaces.IRenderable;
import cz.cloudy.fxengine.physics.PhysicsData;
import cz.cloudy.fxengine.types.Pivot;
import cz.cloudy.fxengine.types.Vector2;
import javafx.scene.image.Image;

import java.io.Serializable;

public abstract class GameObject
        implements IRenderable, Serializable {
    private int         id;
    private String      name;
    private Vector2     position;
    private float       rotation;
    private Vector2     scale;
    private Image       sprite;
    private int         depth;
    private Pivot       pivot;
    private PhysicsData physicsData;

    /**
     * Generates GameObject without specifying name.
     * Name is automatically generated by class name and id.
     */
    protected GameObject() {
        this(null);
    }

    /**
     * Constructs GameObject with specified name.
     * if name is set to null, name is generated by class and id.
     *
     * @param name Object name
     */
    protected GameObject(String name) {
        this.id = GameObjectCollector.getRequestedId()
                                     .getId();
        this.name = name != null ? name : this.getClass()
                                              .getSimpleName() + "_" + id;

        this.position = Vector2.ZERO();
        this.rotation = 0f;
        this.scale = Vector2.SCALE();
        this.sprite = null;
        this.depth = 0;
        this.pivot = Pivot.TOP_LEFT();
        this.physicsData = null;
    }

    public String getName() {
        return name;
    }

    public Vector2 getPosition() {
        return position;
    }

    public void setPosition(Vector2 position) {
        this.position = position;
    }

    public float getRotation() {
        return rotation;
    }

    public void setRotation(float rotation) {
        this.rotation = rotation;
    }

    public Vector2 getScale() {
        return scale;
    }

    public void setScale(Vector2 scale) {
        this.scale = scale;
    }

    public Image getSprite() {
        return sprite;
    }

    public void setSprite(Image sprite) {
        this.sprite = sprite;
    }

    public int getDepth() {
        return depth;
    }

    public void setDepth(int depth) {
        this.depth = depth;
    }

    public Pivot getPivot() {
        return pivot;
    }

    public void setPivot(Pivot pivot) {
        this.pivot = pivot;
    }

    public PhysicsData getPhysicsData() {
        return physicsData;
    }

    public void setPhysicsData(PhysicsData physicsData) {
        this.physicsData = physicsData;
    }

    public Vector2 getAbsolutePosition() {
        return new Vector2(position.x - pivot.x() * (sprite != null ? sprite.getWidth() : 0f),
                           position.y - pivot.y() * (sprite != null ? sprite.getHeight() : 0f));
    }

    public GameObject move(Vector2 offset) {
        this.position.add(offset);
        return this;
    }

    /**
     * Is invoked when GameObject is created.
     */
    public abstract void create();

    /**
     * Is invoked when new frame is rendered.
     */
    public abstract void update();

    /**
     * Is invoked in fixed delta time. It means that it's invoked 60 times every second as to keep 60 frames per second.
     */
    public void fixedUpdate() {

    }

    /**
     * Is invoked when destroy is executed on actual GameObject.
     */
    public abstract void dispose();

    @Override
    public void render() {
        Render.begin()
              .tex()
              .setTexture(sprite)
              .setPosition(position)
              .setSize(scale)
              .setPivot(pivot)
              .end()
              .finish();
    }

    /**
     * Invokes destroy process.
     */
    public final void destroy() {
        dispose();
        GameObjectFactory.disposeObject(this);
    }

    /**
     * Returns automatically generated id for actual object.
     *
     * @return current object's id
     */
    public final int getId() {
        return id;
    }
}
